import "./globals.css";
import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";
import {ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton} from '@clerk/nextjs';
import {ThemeProvider} from "@/components/providers/theme-provider";
import {cn} from "@/lib/utils";

const font = Open_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Team Chat App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
            <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
            <ThemeProvider
                attribute={"class"}
                defaultTheme={"dark"}
                enableSystem={false}
                storageKey={"discord-theme"}
            >
                <header>
                    <SignedOut>
                        <SignInButton/>
                    </SignedOut>
                    <SignedIn>
                        <UserButton/>
                    </SignedIn>
                </header>
                <main>
                    {children}
                </main>
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    );
}
