import "./globals.css";
import type {Metadata} from "next";
import {Open_Sans} from "next/font/google";
import {ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton} from '@clerk/nextjs'
import './globals.css';

const font = Open_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Team Chat App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body>
            <header>
                <SignedOut>
                    <SignInButton/>
                </SignedOut>
                <SignedIn>
                    <UserButton/>
                </SignedIn>
            </header>
            <main>
                {children}
            </main>
            </body>
            </html>
        </ClerkProvider>
    );
}
